AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    # Rubocop is accidentally linting HTML ERB files in Atom Editor https://github.com/AtomLinter/linter-rubocop/issues/48
    - '**/*.html.erb'
    - '**/bin/*'

inherit_from:
  - rubocop/gds-ruby-styleguide.yml
  - rubocop/other-lint.yml
  - rubocop/other-rails.yml
  - rubocop/other-style.yml

# Rubymine disagrees and not sure how to fix Rubymine indentation right now
CaseIndentation:
  Description: Indentation of when in a case/when/[else/]end.
  Enabled: false

LineLength:
  Description: Limit lines to 120 characters.
  Enabled: true
  Max: 120
  Exclude:
    - 'spec/factories/**/*.rb'
    - 'spec/features/**/*_spec.rb'
    - 'spec/models/**/*_spec.rb'
    - 'spec/policies/**/*_spec.rb'
    - 'spec/routing/**/*_spec.rb'

# I don't understand this for now - seems to prevent perfectly reasonable meta-programming
NestedMethodDefinition:
  Enabled: false

# As a web app, as long as the team commit to using well named classes for
# controllers, models etc it should not be necessary to add top-level class documentation.
Documentation:
  Enabled: false

# We shouldn't be committing code with debug statements left in (e.g. byebug or save_and_open_page),
# we don't understand the GDS rationale for disabling this check
Debugger:
  Enabled: true

Style/StringLiterals:
  Exclude:
    - Gemfile

# In specs we like to use the pattern of updating within an expect do block and then asserting a given attribute has
# changed as a result. This requires chaining hence we exclude specs from this rule
Style/MethodCalledOnDoEndBlock:
  Exclude:
    - '**/spec/**/*.rb'
